# Type of opeation system, it could be one of those three
#  - linux
#  - windows-home
#  - windows-pro
#
os: windows-home

# This app keep all state in memory but periodically can unload some information to file.
# Basically it is one of ways to et information about users
statePath: ./

# The param allows to use http interface getting reports The param works if parental-control-web is set up
httpEnable: true

# The param works if parental-control-web is set up
httpPort: 8090

# Interface where UI will be available. The param works if parental-control-web is set up
# The param could also has the next values
#  * means HostAny
#  *4 means HostIPv4
#  !4 means HostIPv4Only
#  *6 means HostIPv6
#  !6 means HostIPv6Only
httpInterface: 127.0.0.1

# PAth to http static content, like html pages and JS scripts
httpStaticPath: ./

commands:
  # Command which is using for notification of user about the time state
  #
  # Template params
  #   {0} is user name/login
  #
  message: "echo"

  # Command which should kill/logout a user
  #
  # Template params
  #   {0} is user name/login/session_id
  kill: "shutdown /s /t 60 /c \"Time is Up!\""

# Path to dynamic config with users information and schedules, by default it is in local 
# file system file:///etc/parental-control/users-config.yml but it could be downloaded from
# any http/https source.
# Examples:
#  file:///etc/parental-control/users-config.yml
#  http://parental-control.link/vasyaod/users-config
usersConfigPath: file://./users-config.yml

# Reload period (sec) of users config, by default 300 sec.
usersConfigRefreshPeriod: 300