#!/bin/bash

set -e

# Post instalation script
systemctl enable parental-control
systemctl start parental-control

pause 1

# Post instalation script
systemctl enable parental-control-web
systemctl start parental-control-web