on: [pull_request]
name: pr-build
jobs:
  build-linux-verson:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}
      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm run build
      - run: sudo apt-get update && sudo apt-get -y install alien
      - run: ./build-deb-schedule              # build package for schedule daemon
      - run: ./build-deb-web                   # build package for web interface
      - run: ./build-deb-all                   # build bundle with schedule daemon web interface
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-linux
          path: |
            dist/*.rpm
            dist/*.deb

  build-windows-pro-verson:
    name: Windows Pro Build
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~\AppData\Roaming\stack
          key: ${{ runner.os }}
      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm run build
      - name: Prepare files for contribution
        shell: cmd
        run: .\build-windows.bat config-windows-pro.yml
      - name: Create installer
        uses: joncloud/makensis-action@v3.6
        with:
          arguments: "/V3"
          script-file: "parental-control.nsi"
      - run: cp .\parental-control-setup.exe ./parental-control-setup-win-pro.exe
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-windows-pro
          path: |
            parental-control-setup-win-pro.exe

  build-windows-home-verson:
    name: Windows Home Build
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~\AppData\Roaming\stack
          key: ${{ runner.os }}
      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm run build
      - name: Prepare files for contribution
        shell: cmd
        run: .\build-windows.bat config-windows-home.yml
      - name: Create installer
        uses: joncloud/makensis-action@v3.6
        with:
          arguments: "/V3"
          script-file: "parental-control.nsi"
      - run: cp .\parental-control-setup.exe ./parental-control-setup-win-home.exe
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-windows-home
          path: |
            parental-control-setup-win-home.exe
